### PR TITLE
Update reschedule route

### PR DESCRIPTION
**Pull request by qux-bbb**
reschedule should use old task route

### CODE REVIEW

**Comment by qux-bbb** [comment]
This pr will disrupt add_pcap and add_static. Please do not merge temporarily.

**Comment by qux-bbb** [comment]
Now this pr will not disrupt add_pcap and add_static.

**Comment by qux-bbb** [comment]
Hello, is there anything wrong with this pr?

**Comment by doomedraven** [comment]
yes need to use tuples instead of lists, but im on PTO so can't update it

**Comment by qux-bbb** [comment]
I adjust it. You can check when you go back. Have a good time!

**Comment by doomedraven** [comment]
Thank you

**Pull request merged**
