### PR TITLE
Update cloning.rst

### PR DESCRIPTION
**Pull request by cccs-mog**

### CODE REVIEW

**Comment by doomedraven** [comment]
thank you, i will add that configurable from the config tomorrow, so no need to change the disguise.py by hand, aftar that i will mode this and merge

**Comment by doomedraven** [comment]
could you test the update plz before i merge?

**Comment by doomedraven** [comment]
\c @dsecuma for headups

**Comment by cccs-mog** [comment]
So I tested the upgrade and seem to work fine. Wondering what the goal of the config section gateways is ? Is it related ? Or maybe disguise should have his own section ?(Don't remember if the sections are for server side auxiliary) Small details but regardless of the presentation it work good now.

**Comment by doomedraven** [comment]
ok, removed get as it useless as we have default value in config anyway, thank you going to merge

**Pull request merged**
