### PR TITLE
Auxiliary and machinery modules cleanup

### PR DESCRIPTION
**Pull request by TheMythologist**
Some changes that I made:
- Removed redundant outdated Python checks
- Shifted code blocks to remove unnecessary indentations

Should be more readable in general, let me know if you disagree with any of the changes made

### CODE REVIEW

**Comment by doomedraven** [comment]
looks good, thank you, just few things

1. `return None` is the same that just `return` as far as i know
2. about `subproces.check_output` if we remove return value storage, it will print to stdout, so i have 2 suggestions.
    * add `stdout=DEVNUL` <- i prefer this one
    * or `_ = subprocess.check_output`
    
what do you think?

**Comment by TheMythologist** [comment]
I think we should stick to using `return None` because the function does return None instead of simply returning (which I would use only in places to break out of loops). I will add subprocess to redirect its stdout to `DEVNULL` , thanks for the input :)

**Comment by doomedraven** [comment]
ok make sense, thank you

**Comment by TheMythologist** [comment]
Actually, before merging, I took a look and I don't think `subprocess.check_output` prints to stdout, I'll make changes accordingly

**Comment by doomedraven** [comment]
well i tested before make comment, and it gave me outout in stdout

**Comment by TheMythologist** [comment]
May I know what's the output/command you're running? I can't seem to replicate on my end

**Comment by doomedraven** [comment]
to simulate ssh and cat

```
>>> subprocess.check_output(["ssh", "<removed>",  "cat", "/etc/passwd"])
b"root:x:0:0:root:/root:/bin/ba<removed>
```

**Comment by doomedraven** [comment]
anything that is not stored to output will print, we could change it from check_output as it forces subprocess to return output and not just return comamnd, but with stdout=DEVNUL if should be fine

**Comment by TheMythologist** [comment]
Ahh I see it's because you're running it in the Python interpreter, which will print the return value of the function you're running. Try running the command `subprocess.check_output(["ssh", "<removed>",  "cat", "/etc/passwd"])` in a python file and running the python file itself from the command line and you won't see the output!

**Comment by doomedraven** [comment]
ok yes you are right

**Comment by doomedraven** [comment]
i have cleaned a bit more vbox machinery, but i hope nobody uses that as we not even care/supports that https://docs.oracle.com/en/virtualization/virtualbox/6.0/user/vboxmanage-debugvm.html

**Pull request merged**
