### PR TITLE
Adding utility to download parsers, to be used with cronjob

### PR DESCRIPTION
**Pull request by cccs-kevin**
Addresses https://cccs.atlassian.net/browse/AL-2719

Testing in production for a bit before making PR ready for review

### CODE REVIEW

**Comment by kevoreilly** [comment]
Curious as to what this addresses, alas I cannot access that link...

**Comment by cccs-kevin** [comment]
> Curious as to what this addresses, alas I cannot access that link...

It's a method of downloading the latest parsers, without updating CAPE itself, similar to the `download_yara.py` utility

**Comment by VVelox** [comment]
hmm... would not it be better to maybe move that out into the other repo?

That said I may be wrong, don't these often times require possible upgrades/updates when it comes to the depends, so may not work well? May be wrong on that bit though.

**Comment by doomedraven** [comment]
that was discussed, yes they might have extra deps, so user that uses this utility uses it on his own risk :)

**Comment by cccs-kevin** [comment]
Yes fair point, I'll move this utility as well as the `download_yara.py` utility to the community repo!

**Comment by cccs-kevin** [comment]
Community PR: https://github.com/CAPESandbox/community/pull/390

**Pull request merged**
