### PR TITLE
Using pipes instead of commas since get_options cannot handle comma d…

### PR DESCRIPTION
**Pull request by cccs-kevin**
…elimiters per option

https://github.com/kevoreilly/CAPEv2/blob/9f252cc4817977055188a4590a106e5229243bfb/lib/cuckoo/common/utils.py#L853

### CODE REVIEW

**Comment by doomedraven** [comment]
so that would be function=1|2|3?

**Comment by cccs-kevin** [comment]
> so that would be function=1|2|3?

Correct!

**Comment by kevoreilly** [comment]
But aren't colons used for this elsewhere, e.g. exclude-apis=func1:func2

**Comment by doomedraven** [comment]
ah yes that true

**Comment by doomedraven** [comment]
i have replaced pipe by colon to keep it consistent

**Comment by kevoreilly** [comment]
Thanks 👍

**Comment by cccs-kevin** [comment]
Thanks team!

**Comment by kevoreilly** [comment]
I do wonder if some more brainstorming could be useful on the tricky subject of 'hidden' exports - looks like my recent feature for using yara to select an export will be undermined by the AL solution picking another export first.

**Comment by cccs-kevin** [comment]
> I do wonder if some more brainstorming could be useful on the tricky subject of 'hidden' exports - looks like my recent feature for using yara to select an export will be undermined by the AL solution picking another export first.

This commit? https://github.com/kevoreilly/CAPEv2/commit/0b1a634709535ce004475806968382fe349ef780

**Comment by kevoreilly** [comment]
Well that is one example of the technique. To understand its mechanism the relevanr capemon commit is: https://github.com/kevoreilly/capemon/commit/64d21309ad498819a678e640324c71c5feeba93b

This mechanism relies on the dll being submitted with the default export '#1' and then allowing an address set by monitor yara to override the return value from the LdrGetProcedureAddress hook.

**Comment by kevoreilly** [comment]
@doomedraven also uses another solution at his $dayjob whereby multiple exports are executed in multi-threaded fashion by a custom compiled loader - this is more similar to the AL logic as it relies on brute force or other more generic tests. The ideal would surely be to allow for both mechanisms to work alongside each other harmoniously.

**Comment by cccs-kevin** [comment]
Right right. The AL solution is what our reverse engineering team came up with to cover all Dlls that we receive for analysis. I agree, it would ideal to have a "best of both worlds" solution.

**Pull request merged**
