### PR TITLE
Add submission of vhd files

### PR DESCRIPTION
**Pull request by enzok**
test sample 

7075e9c8713483fc0613863f6cb27089

### CODE REVIEW

**Comment by doomedraven** [comment]
nice, this requires `guestfs-python` no?

**Comment by doomedraven** [comment]
i think this would be nice to move to my sflock repo so we can use it outside of cape also no?

**Comment by doomedraven** [comment]
i can do that for sflock

**Comment by enzok** [comment]
Yes python-guestfs is required.

**Comment by enzok** [comment]
I didn't add it to sflock because of the guestfs requirement. Just added to decrpyt.py for simplicity.

**Comment by enzok** [comment]
Cool if you want to add to your sflock repo though.

**Comment by doomedraven** [comment]
well it easy to handle with try except if user have it installed, i will integrate that, to make cape more cleaner and im using sflock in another project so it will be more useful, will do this this days, thanks a lot for PR

**Comment by doomedraven** [comment]
i will need to test it, but prototype is already done https://github.com/doomedraven/sflock/commit/c8bbf0fd11fff9818ba9a1b5e14864fc89bd15e6

**Comment by enzok** [comment]
You should also add .vhdx in list of extensions.

**Comment by doomedraven** [comment]
thansk, will add it

**Comment by doomedraven** [comment]
@enzok can you please test it with https://github.com/doomedraven/sflock?

**Comment by doomedraven** [comment]
btw @enzok 7zip works with this one just fine so im gonna change sflock once again to handle that with 7zip instead of extra deps

**Comment by doomedraven** [comment]
done, it now without dependencies and works with 7z :), so please update sflock, im closing the PR

```
>>> pp(q.children[0].to_dict())
{'children': [],
 'duplicate': False,
 'error': None,
 'extrpath': ['FedEx pending delivery for you.exe'],
 'filename': 'FedEx pending delivery for you.exe',
 'filepath': None,
 'finger': {'magic': 'PE32 executable (GUI) Intel 80386, for MS Windows',
            'magic_human': 'PE32 executable (GUI) Intel 80386 (for MS Windows)',
            'mime': 'application/x-dosexec',
            'mime_human': 'dosexec'},
 'package': 'exe',
 'parentdirs': [],
 'password': None,
 'platform': 'windows',
 'preview': True,
 'relaname': 'FedEx pending delivery for you.exe',
 'relapath': 'FedEx pending delivery for you.exe',
 'selected': False,
 'sha256': 'f500df00ac0bac4da7df838c6bbc3a5ce330cfaa26665638701ef1412570afaf',
 'size': 1520128L,
 'type': 'file'}
```

**Pull request closed without merging**
