### PR TITLE
feat: new zip_compound package

### PR DESCRIPTION
**Pull request by TheMythologist**
# New package: `zip_compound`
Samples with this package need a configuration.json file to dictate where the files are
Sample configuration.json file can be found at [tests/zip_compound/files/example_config.json](https://github.com/TheMythologist/CAPEv2/blob/e310686ed9694d718bdb6f167d25f4b50d0913c8/tests/zip_compound/files/example_config.json)

### CODE REVIEW

**Comment by TheMythologist** [comment]
On a side note, I think the cached venv is broken in the github actions

**Comment by doomedraven** [comment]
lets see if this fixes it https://github.com/kevoreilly/CAPEv2/blob/master/.github/workflows/python-package.yml

**Comment by cccs-kevin** [comment]
Don't forget to add this package to the docs! https://capev2.readthedocs.io/en/latest/usage/packages.html

**Comment by TheMythologist** [comment]
Regarding the broken CI, it may (hopefully, crossing my fingers) fixed after merging the dependabot update

**Comment by doomedraven** [comment]
which update?

**Comment by TheMythologist** [comment]
The dependabot update (it's a new poetry.lock file so new cache)

**Comment by kevoreilly** [comment]
tlsdump broken here fixed in https://github.com/kevoreilly/CAPEv2/commit/ada7993cc4b140c06617562aeb2a3151544fa1b2

**Pull request merged**
