### PR TITLE
Fix yara hit function parameter

### PR DESCRIPTION
**Pull request by enzok**
function is also called from processing.py

### CODE REVIEW

**Comment by doomedraven** [comment]
where it fails? i would like to see log logs

```
 grep -r static_config_parsers .
./lib/cuckoo/common/cape_utils.py:def static_config_parsers(yara_hit, file_data):
./lib/cuckoo/common/cape_utils.py:            config = static_config_parsers(hit["name"], file_data)
./modules/processing/CAPE.py:                config_tmp = static_config_parsers(cape_name, file_data)
./modules/processing/CAPE.py:            tmp_config = static_config_parsers(hit["name"].replace("_", " "), file_data)
```

**Comment by doomedraven** [comment]
asl as you can see it will break the rest as it expects name already not the hit object

**Comment by enzok** [comment]
strange my CAPE.py has this:       tmp_config = static_config_parsers(hit, file_data)
I'll verify any merges with that file.

**Comment by enzok** [comment]
Found a bad merge. Closing this request.

**Comment by doomedraven** [comment]
ok, thanks anyway ;)

**Pull request closed without merging**
