### PR TITLE
update description & cape_type info for IcedIDStage1

### PR DESCRIPTION
**Pull request by r0ny123**

### CODE REVIEW

**Comment by kevoreilly** [comment]
I'm afraid cape_type field is not intended for divisions within a malware family, like 'Stage 1' since this is the name that becomes the 'detection' - it was a mistake to allow this historically with IcedId but I will fix this and get back to the place where 'detections' are pure malware family names and nothing else, as that is the design.

**Comment by kevoreilly** [comment]
Since the description is also captured/displayed this is the place for any extra info so it can displayed if useful, but won't affect the overall detection name from being just the family.

**Comment by doomedraven** [comment]
isn't this is the same as photoloader or gziploader? i mean stage 1?

**Comment by r0ny123** [comment]
Yes, in this case it is gziploader.

**Comment by kevoreilly** [comment]
Maybe - I didn't write or merge those. It's tricky to maintain this project to the design standard! I will correct those too.

Consider this for yet another reason these are bad: currently in cape there is only room for one family in detection. Thus if we have stage 1 then stage 2, which do we detect? It would end up saying stage 1 when stage 2 is also in there...

**Comment by doomedraven** [comment]
yes is still a work to do to show all detections, but i have somethign that you will like ;) soon when i will have more time to finish

**Pull request closed without merging**
