### PR TITLE
Added logic to fix potential race condition when provisioning new EC2…

### PR DESCRIPTION
**Pull request by JaminB**
- Addresses some issues parsing blanked out values in the `aws.conf` file.
- Addresses intermittent errors with aws machinery where newly provisioned EC2 instances would occasionally raise ResourceNotFound errors when attempting to pull information about the instance.

### CODE REVIEW

**Comment by JaminB** [comment]
AWS machinery is much more stable with these changes; I have submitted over 1000 files with 3 instances running concurrently.

**Comment by doomedraven** [comment]
Hello thank you. How is the performance on AWS?

**Comment by JaminB** [comment]
Performance is good, no longer intermittently crashing. I'll continue to scale up and report back.

**Comment by doomedraven** [comment]
nice, could you help us with aws docs at least some minimal docs for quick start?

**Comment by JaminB** [comment]
Sorry, just seeing these comments. Yes, I can help out with the AWS docs and will include a short video.

**Comment by doomedraven** [comment]
Thank you a lot

**Pull request merged**
