### PR TITLE
Add Tracee eBPF threat detection for Linux Dynamic Analysis

### PR DESCRIPTION
**Pull request by theoleecj2**
# Tracee Pull Request

This pull request integrates [Aqua Security Tracee](https://www.aquasec.com/products/tracee/), an eBPF-based threat detection engine with built-in signatures, into CAPEv2 for Linux dynamic analysis to complement the existing `strace` implementation. The log streaming implementation is similar to @winson0123's `strace` streaming to prevent ransomware's encryption of the logs.

Please comment if you see any issues.

## Screenshots and demo

*Screenshot of the Tracee Behaviour UI*
image

*Demonstration of a captured kernel module (which was encrypted and stored only in memory)*
image

## Rationale

In no order of importance:

- Tracee has functionality to **capture artifacts** such as loaded kernel modules, suspicious memory regions and eBPF programs in their **run-time state**, allowing their **easy extraction even from packed and encrypted malwares**, aiding in dynamic analysis
- Powerful filtering UI based on datatables JavaScript library
    - Opted for client-side data filtering for performance reasons and to ease server load
    - Compressed (gzipped) data format for storage in CAPE report (~10x compression and bandwidth savings due to JSON log format)
    - Able to store uncompressed fields if required, e.g. for integration into CAPE signatures (future work)
- Tracee has advanced [built-in signatures](https://aquasecurity.github.io/tracee/latest/docs/events/builtin/signatures/) for many suspicious behaviours such as:
    - Dynamic Code Loading
    - Fileless Execution
    - Hidden File Created
    - Syscall Table Hooking
    - `kallsyms_lookup_name` -  it could be used in some rootkits, likely until recently... (it's an [interesting story](https://github.com/xcellerator/linux_kernel_hacking/issues/3))
    - **Illegitimate Shell** - detect instances where a web server program spawns a shell
    - **Kernel Module Loading** - new kernel module loaded (possible kernel rookits)
    - **Loader Preload** - identifies manipulation of `LD_PRELOAD` and `LD_LIBRARY_PATH` environment variables, or similar methods which can potentially be leveraged for code injection
    - **Process VM Write** - detect potential code injection attacks using the `process_vm_writev` syscall
    - **Scheduled Task Modification** - like cron
    - **Standard I/O Over Socket** - potential remote shell
    - **Many more...**
- Built-in signatures make it easier for users to identify and narrow down suspicious behaviours compared to sifting through many syscalls
- Tracee operates at the eBPF level, making it harder (but not impossible) to detect than `strace` by malware.

## Trying it out

To get started, use the branch theoleecj2/CAPEv2 -> tracee.

Run `docker pull docker.io/aquasec/tracee:0.20.0` in a Ubuntu VM which already has the CAPE agent running. For best results, use Ubuntu 20.04.

> **Side Note**: Some rootkits and malware you may find online may require `kallsyms_lookup_name` which is affected in Linux kernel versions > 5.7. See [here](https://github.com/xcellerator/linux_kernel_hacking/issues/3) for more information.

Then `docker image tag aquasec/tracee:0.20.0 aquasec/tracee:latest` to record v0.20.0 as the latest.

Add `tracee_linux = yes` to the auxiliary.conf's `[auxiliary_modules]` section and

```yaml
[tracee]
enabled = yes
```

into processing.conf.

You can obtain a **live malware sample** for Linux to load into CAPEv2 from https://bazaar.abuse.ch/sample/bd0141e88a0d56b508bc52db4dab68a49b6027a486e4d9514ec0db006fe71eed/. Please be careful with this file as it's an actual malware. We do not take responsibility for anything that goes wrong.

For further demonstration, you can try https://github.com/citronneur/pamspy which loads an eBPF program to steal credentials. The eBPF should be captured by Tracee in 'Dropped Files'.

## Limitations

Tracee sometimes does not de-reference pointers while `strace` can capture the contents. The Tracee implementation here is not 100% reliable, and we are working on improving it (for instance, we have added a health check).

## Common Issues

You need to have the `strace` auxiliary module enabled. Processing for `strace` need not be enabled, but you can enable it to observe the Tracee module's weaknesses and strengths compared to it.

The event capturing is not 100% reliable. If a task's Tracee output looks incorrect, please try again.

Check that you have `/opt/CAPEv2/data/linux/linux-syscalls.json`. If not, you can obtain it from https://raw.githubusercontent.com/mebeim/linux-syscalls/master/db/x86/64/x64/v6.5/table.json.

### CODE REVIEW

**Comment by kevoreilly** [comment]
Thank you ❤️

**Comment by doomedraven** [comment]
hello, thank you for such a great contribution, i will merge it , but some parts will be moved to community repo to clarify that is not done by core devs

**Comment by Dasher-zdh** [comment]
log
2025-04-28 09:50:56,040 [root] DEBUG: Starting analyzer from: /tmphhcukjcn
2025-04-28 09:50:56,041 [root] DEBUG: Storing results at: /tmp/TLzwjbKO
2025-04-28 09:50:56,050 [root] DEBUG: Importing auxiliary module "modules.auxiliary.filecollector"...
2025-04-28 09:50:56,149 [root] DEBUG: Importing auxiliary module "modules.auxiliary.human"...
2025-04-28 09:50:56,639 [root] DEBUG: Importing auxiliary module "modules.auxiliary.screenshots"...
2025-04-28 09:50:56,936 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageChops'
2025-04-28 09:50:56,937 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageDraw'
2025-04-28 09:50:56,937 [lib.api.screenshot] INFO: Please upgrade Pillow to >= 5.4.1 for best performance
2025-04-28 09:50:57,074 [modules.auxiliary.filecollector] INFO: FileCollector run started
2025-04-28 09:50:57,135 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir srv
2025-04-28 09:50:57,136 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir lost+found
2025-04-28 09:50:57,141 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir snap
2025-04-28 09:51:01,382 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir tmpjz1jkxdc
2025-04-28 09:51:01,387 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir libx32
2025-04-28 09:51:01,388 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir bin
2025-04-28 09:51:01,388 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir opt
2025-04-28 09:51:01,389 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir home
2025-04-28 09:51:01,508 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir .Library
2025-04-28 09:51:01,509 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir cdrom
2025-04-28 09:51:01,509 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir lib32
2025-04-28 09:51:01,510 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir media
2025-04-28 09:51:01,510 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir sbin
2025-04-28 09:51:01,511 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir boot
2025-04-28 09:51:01,513 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir tmphhcukjcn
2025-04-28 09:51:01,514 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir etc
2025-04-28 09:51:01,607 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir tmp
2025-04-28 09:51:01,610 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir root
2025-04-28 09:51:01,673 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir mnt
2025-04-28 09:51:01,673 [modules.auxiliary.filecollector] INFO: FileCollector setup complete
2025-04-28 09:51:02,076 [root] DEBUG: Initialized auxiliary module "FileCollector"
2025-04-28 09:51:02,077 [root] DEBUG: Trying to start auxiliary module "FileCollector"...
2025-04-28 09:51:02,078 [root] DEBUG: Started auxiliary module "FileCollector"
2025-04-28 09:51:02,080 [modules.auxiliary.human] DEBUG: Human init complete
2025-04-28 09:51:02,081 [root] DEBUG: Initialized auxiliary module "Human"
2025-04-28 09:51:02,081 [root] DEBUG: Trying to start auxiliary module "Human"...
2025-04-28 09:51:02,082 [root] DEBUG: Started auxiliary module "Human"
2025-04-28 09:51:02,083 [root] DEBUG: Initialized auxiliary module "Screenshots"
2025-04-28 09:51:02,084 [root] DEBUG: Trying to start auxiliary module "Screenshots"...
2025-04-28 09:51:02,084 [asyncio] DEBUG: Using selector: EpollSelector
2025-04-28 09:51:02,085 [root] DEBUG: Started auxiliary module "Screenshots"
2025-04-28 09:51:02,092 [lib.core.packages] INFO: sh -c
2025-04-28 09:51:02,092 [lib.core.packages] INFO: sudo strace -o /dev/stderr -s 800  -ttf sh -c /tmp/bd0141e88a0d56b508bc.elf
2025-04-28 09:51:02,095 [lib.core.packages] INFO: Process started with strace
2025-04-28 09:51:02,096 [root] INFO: Added new process to list with pid: 2274
2025-04-28 09:51:02,348 [root] INFO: New child process detected: 2280
2025-04-28 09:51:02,769 [lib.common.results] INFO: File /.Library/SystemServices/updateSystem size is 40960, Max size: 100000000
2025-04-28 09:51:02,786 [lib.common.results] INFO: File /.Library/SystemServices/updateSystem size is 865144, Max size: 100000000
2025-04-28 09:54:22,430 [root] INFO: Analysis timeout hit, terminating analysis
2025-04-28 09:54:22,431 [root] INFO: Stopping auxiliary modules
2025-04-28 09:54:22,433 [root] INFO: Stopping auxiliary module: FileCollector
2025-04-28 09:54:23,201 [lib.core.packages] INFO: Strace streaming connection has been closed
2025-04-28 09:54:29,436 [root] INFO: Stopping auxiliary module: Human
2025-04-28 09:54:29,437 [root] INFO: Stopping auxiliary module: Screenshots
2025-04-28 09:54:29,437 [root] INFO: Finishing auxiliary modules
2025-04-28 09:54:29,438 [lib.common.results] WARNING: File /sslkeylog.log doesn't exist anymore
2025-04-28 09:54:29,438 [root] INFO: Analysis completed

**Comment by superonion7890** [comment]
> # Tracee Pull Request
> This pull request integrates [Aqua Security Tracee](https://www.aquasec.com/products/tracee/), an eBPF-based threat detection engine with built-in signatures, into CAPEv2 for Linux dynamic analysis to complement the existing `strace` implementation. The log streaming implementation is similar to @winson0123's `strace` streaming to prevent ransomware's encryption of the logs.
> 
> Please comment if you see any issues.
> 
> ## Screenshots and demo
> _Screenshot of the Tracee Behaviour UI_ image
> 
> _Demonstration of a captured kernel module (which was encrypted and stored only in memory)_ image
> 
> ## Rationale
> In no order of importance:
> 
> * Tracee has functionality to **capture artifacts** such as loaded kernel modules, suspicious memory regions and eBPF programs in their **run-time state**, allowing their **easy extraction even from packed and encrypted malwares**, aiding in dynamic analysis
> * Powerful filtering UI based on datatables JavaScript library
>   
>   * Opted for client-side data filtering for performance reasons and to ease server load
>   * Compressed (gzipped) data format for storage in CAPE report (~10x compression and bandwidth savings due to JSON log format)
>   * Able to store uncompressed fields if required, e.g. for integration into CAPE signatures (future work)
> * Tracee has advanced [built-in signatures](https://aquasecurity.github.io/tracee/latest/docs/events/builtin/signatures/) for many suspicious behaviours such as:
>   
>   * Dynamic Code Loading
>   * Fileless Execution
>   * Hidden File Created
>   * Syscall Table Hooking
>   * `kallsyms_lookup_name` -  it could be used in some rootkits, likely until recently... (it's an [interesting story](https://github.com/xcellerator/linux_kernel_hacking/issues/3))
>   * **Illegitimate Shell** - detect instances where a web server program spawns a shell
>   * **Kernel Module Loading** - new kernel module loaded (possible kernel rookits)
>   * **Loader Preload** - identifies manipulation of `LD_PRELOAD` and `LD_LIBRARY_PATH` environment variables, or similar methods which can potentially be leveraged for code injection
>   * **Process VM Write** - detect potential code injection attacks using the `process_vm_writev` syscall
>   * **Scheduled Task Modification** - like cron
>   * **Standard I/O Over Socket** - potential remote shell
>   * **Many more...**
> * Built-in signatures make it easier for users to identify and narrow down suspicious behaviours compared to sifting through many syscalls
> * Tracee operates at the eBPF level, making it harder (but not impossible) to detect than `strace` by malware.
> 
> ## Trying it out
> To get started, use the branch theoleecj2/CAPEv2 -> tracee.
> 
> Run `docker pull docker.io/aquasec/tracee:0.20.0` in a Ubuntu VM which already has the CAPE agent running. For best results, use Ubuntu 20.04.
> 
> > **Side Note**: Some rootkits and malware you may find online may require `kallsyms_lookup_name` which is affected in Linux kernel versions > 5.7. See [here](https://github.com/xcellerator/linux_kernel_hacking/issues/3) for more information.
> 
> Then `docker image tag aquasec/tracee:0.20.0 aquasec/tracee:latest` to record v0.20.0 as the latest.
> 
> Add `tracee_linux = yes` to the auxiliary.conf's `[auxiliary_modules]` section and
> 
> ```yaml
> [tracee]
> enabled = yes
> ```
> 
> into processing.conf.
> 
> You can obtain a **live malware sample** for Linux to load into CAPEv2 from https://bazaar.abuse.ch/sample/bd0141e88a0d56b508bc52db4dab68a49b6027a486e4d9514ec0db006fe71eed/. Please be careful with this file as it's an actual malware. We do not take responsibility for anything that goes wrong.
> 
> For further demonstration, you can try https://github.com/citronneur/pamspy which loads an eBPF program to steal credentials. The eBPF should be captured by Tracee in 'Dropped Files'.
> 
> ## Limitations
> Tracee sometimes does not de-reference pointers while `strace` can capture the contents. The Tracee implementation here is not 100% reliable, and we are working on improving it (for instance, we have added a health check).
> 
> ## Common Issues
> You need to have the `strace` auxiliary module enabled. Processing for `strace` need not be enabled, but you can enable it to observe the Tracee module's weaknesses and strengths compared to it.
> 
> The event capturing is not 100% reliable. If a task's Tracee output looks incorrect, please try again.
> 
> Check that you have `/opt/CAPEv2/data/linux/linux-syscalls.json`. If not, you can obtain it from https://raw.githubusercontent.com/mebeim/linux-syscalls/master/db/x86/64/x64/v6.5/table.json.

May I ask the step or guide for Linux Guest Setting. I've following the step from https://capev2.readthedocs.io/en/latest/installation/guest/linux.html but if I submit .ELF file the cape.service say like this:

ERROR: PE type not recognised: 'DOS Header magic not found'

Whats the solution? Thanks

**Comment by winson0123** [comment]
Seems like your issue may be tied to https://github.com/kevoreilly/CAPEv2/issues/2589.

Bumping your `sflock` version may be a solution for now:
https://github.com/kevoreilly/CAPEv2/issues/2589#issuecomment-2886990614

**Comment by superonion7890** [comment]
> Seems like your issue may be tied to https://github.com/kevoreilly/CAPEv2/issues/2589.
> 
> Bumping your `sflock` version may be a solution for now:
> https://github.com/kevoreilly/CAPEv2/issues/2589#issuecomment-2886990614

Thanks for your comment. I've try it, but the error message is still show. The error say like as the CAPE service cannot identifying the .ELF binary or .ELF Header, then whats the solution? Is it because CAPE didn't support the . ELF analysis?

**Comment by winson0123** [comment]
Have you tried submitting your sample with the selected `Analysis Package` option to be `bash`?

**Comment by superonion7890** [comment]
> Have you tried submitting your sample with the selected `Analysis Package` option to be `bash`?

No, I don't set the analysis package, bacause I think the .elf package is not available, so I choose the Detect Automatically Package

**Comment by superonion7890** [comment]
> Have you tried submitting your sample with the selected `Analysis Package` option to be `bash`?

Thanks for your recomendation, I will try it to change the Package option into bash execution

**Comment by superonion7890** [comment]
> Have you tried submitting your sample with the selected `Analysis Package` option to be `bash`?

I've try to resubmit the malware then choose the package type, but, the process is still give error with message same lke before, like this

image

**Comment by jjilson** [comment]
Log:
2025-09-22 14:10:45,005 [root] DEBUG: Starting analyzer from: /cr8mee3r
2025-09-22 14:10:45,006 [root] DEBUG: Storing results at: /tmp/XFfABqotb
2025-09-22 14:10:45,013 [root] DEBUG: Importing auxiliary module "modules.auxiliary.filecollector"...
2025-09-22 14:10:45,096 [root] DEBUG: Importing auxiliary module "modules.auxiliary.human"...
2025-09-22 14:10:45,249 [root] DEBUG: Importing auxiliary module "modules.auxiliary.screenshots"...
2025-09-22 14:10:45,295 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageChops'
2025-09-22 14:10:45,297 [lib.api.screenshot] DEBUG: Importing 'PIL.ImageDraw'
2025-09-22 14:10:45,297 [lib.api.screenshot] INFO: Please upgrade Pillow to >= 5.4.1 for best performance
2025-09-22 14:10:45,349 [root] DEBUG: Importing auxiliary module "modules.auxiliary.sysmon"...
2025-09-22 14:10:45,351 [root] DEBUG: Importing auxiliary module "modules.auxiliary.tracee"...
2025-09-22 14:10:45,355 [modules.auxiliary.filecollector] INFO: FileCollector run started
2025-09-22 14:10:45,364 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir snap
2025-09-22 14:10:46,644 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir root
2025-09-22 14:10:46,692 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir s1p3_whz
2025-09-22 14:10:46,696 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir 6tsmu_9i
2025-09-22 14:10:46,700 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir mnt
2025-09-22 14:10:46,701 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir ahjr7_14
2025-09-22 14:10:46,704 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir media
2025-09-22 14:10:46,705 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir sbin.usr-is-merged
2025-09-22 14:10:46,705 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir cr8mee3r
2025-09-22 14:10:46,706 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir srv
2025-09-22 14:10:46,706 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir .Library
2025-09-22 14:10:46,707 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir boot
2025-09-22 14:10:46,709 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir d9w5qvow
2025-09-22 14:10:46,713 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir etc
2025-09-22 14:10:46,803 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir kpdzasrr
2025-09-22 14:10:46,807 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir home
2025-09-22 14:10:46,886 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir lib.usr-is-merged
2025-09-22 14:10:46,886 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir sbin
2025-09-22 14:10:46,886 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir bin.usr-is-merged
2025-09-22 14:10:46,887 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir cdrom
2025-09-22 14:10:46,887 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir bin
2025-09-22 14:10:46,887 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir lost+found
2025-09-22 14:10:46,888 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir xcz3xob1
2025-09-22 14:10:46,892 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir tkgyvp3u
2025-09-22 14:10:46,897 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir opt
2025-09-22 14:10:46,898 [modules.auxiliary.filecollector] INFO: FileCollector trying to watch dir tmp
2025-09-22 14:10:46,900 [modules.auxiliary.filecollector] INFO: FileCollector setup complete
2025-09-22 14:10:47,356 [root] DEBUG: Initialized auxiliary module "FileCollector"
2025-09-22 14:10:47,358 [root] DEBUG: Trying to start auxiliary module "FileCollector"...
2025-09-22 14:10:47,359 [root] DEBUG: Started auxiliary module "FileCollector"
2025-09-22 14:10:47,362 [modules.auxiliary.human] DEBUG: Human init complete
2025-09-22 14:10:47,364 [root] DEBUG: Initialized auxiliary module "Human"
2025-09-22 14:10:47,366 [root] DEBUG: Trying to start auxiliary module "Human"...
2025-09-22 14:10:47,366 [root] DEBUG: Started auxiliary module "Human"
2025-09-22 14:10:47,367 [root] DEBUG: Initialized auxiliary module "Screenshots"
2025-09-22 14:10:47,368 [root] DEBUG: Trying to start auxiliary module "Screenshots"...
2025-09-22 14:10:47,371 [asyncio] DEBUG: Using selector: EpollSelector
2025-09-22 14:10:47,374 [root] DEBUG: Started auxiliary module "Screenshots"
2025-09-22 14:10:47,374 [root] DEBUG: Initialized auxiliary module "Sysmon"
2025-09-22 14:10:47,376 [root] DEBUG: Trying to start auxiliary module "Sysmon"...
2025-09-22 14:10:47,378 [root] DEBUG: Started auxiliary module "Sysmon"
2025-09-22 14:10:47,380 [modules.auxiliary.tracee] INFO: docker start
2025-09-22 14:10:47,390 [modules.auxiliary.tracee] INFO: True
2025-09-22 14:10:47,392 [modules.auxiliary.tracee] INFO: Tracee
2025-09-22 14:10:47,395 [root] DEBUG: Initialized auxiliary module "Docker"
2025-09-22 14:10:47,398 [root] DEBUG: Trying to start auxiliary module "Docker"...
2025-09-22 14:10:47,514 [modules.auxiliary.tracee] DEBUG: Starting docker container
2025-09-22 14:10:47,515 [modules.auxiliary.tracee] DEBUG: sudo docker run --name tracee -d --pid=host --cgroupns=host --privileged -v /etc/os-release:/etc/os-release-host:ro -v /cr8mee3r/tracee-artifacts/:/tmp/tracee/out/host -v /var/run:/var/run:ro -v /cr8mee3r/modules/auxiliary/tracee:/policy aquasec/tracee:latest --output json --output option:parse-arguments,exec-env,exec-hash --policy /policy/policy.yml --cache cache-type=mem --cache mem-cache-size=1024 --capture bpf --capture module
2025-09-22 14:10:48,152 [modules.auxiliary.tracee] DEBUG: Docker container started: 7ba9c5608d4a2868c0bc475b5f2ccca5cd25a335f44b68caa598f41f5bf9dd7f

2025-09-22 14:10:58,220 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:10:58,274 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:11:08,312 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:11:08,366 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:11:18,387 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:11:18,449 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:11:28,478 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:11:28,524 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:11:38,533 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:11:38,579 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:11:48,591 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:11:48,654 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:11:58,707 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:11:58,756 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:12:08,768 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:12:08,816 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:12:18,825 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:12:18,869 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:12:28,880 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:12:28,925 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:12:38,936 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:12:38,990 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:12:49,006 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:12:49,053 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:12:59,074 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:12:59,126 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:13:09,157 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:13:09,217 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:13:19,267 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:13:19,313 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:13:29,324 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:13:29,377 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:13:39,390 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:13:39,440 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:13:49,464 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:13:49,509 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:13:59,559 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:13:59,611 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:14:09,616 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:14:09,656 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:14:19,677 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:14:19,736 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:14:29,768 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:14:29,819 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:14:39,861 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:14:39,913 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:14:49,950 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:14:50,006 [modules.auxiliary.tracee] INFO: 
2025-09-22 14:15:00,011 [modules.auxiliary.tracee] INFO: tracee-health-check-1903ae

2025-09-22 14:15:00,056 [modules.auxiliary.tracee] INFO: 



I've enabled tracee properly, made sure to install it correctly in the Linux VM, and properly configured it in the auxiliary.conf and processing.conf. Strace is also enabled. I'm not sure why I'm not getting back any signatures or meaningful data. For some reason, tracee just doesn't seem to work. I would appreciate any help or insight to fixing this. Thank you!

**Pull request merged**
