### PR TITLE
drarft: Various fixes

### PR DESCRIPTION
**Pull request by davidt99**
Few fixes:
- Performance improvement for querying cape task status
- Cleanup mongo by default. This is breaking changes in a way since the flag is changed now to `--dont-delete-mongo`
- Handle network error in the scheduler
- Remove FP of process hollowing for acrobat reader

### CODE REVIEW

**Comment by doomedraven** [comment]
hey thanks, small note, `--dont-delete-mongo` will set to try, but it will set delete mongo instead of not delete https://github.com/intezer/CAPEv2/blob/8d7fdc1021464873e8297728915876403f64b067/utils/cleaners.py#L97

**Comment by doomedraven** [comment]
i think we maybe just should set default to false or idk, right now im on PTO so once i will be back i can check that, but i had to change that recently bcz it wasn't working properly

**Comment by davidt99** [comment]
No rush merging this so enjoy your PTO.
I'll look into that, it might be a bad merge on our side so don't merge that yet.

**Comment by doomedraven** [comment]
so @davidt99 my idea is to not remove mongo data by default, to remove it i prefer to set flag to remove, than set flag to not remove it. so if you revert that cleaners change i will merge

**Comment by doomedraven** [comment]
i don't have permission to push edits to this PR

**Comment by doomedraven** [comment]
i have merged and changed cleaners after merge, thanks for update

**Comment by doomedraven** [comment]
btw

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/CAPEv2/web/./apiv2/views.py", line 2012, in cuckoo_status
    tasks_dict_with_counts = db.get_tasks_status_count()
  File "/opt/CAPEv2/lib/cuckoo/common/utils.py", line 977, in inner
    return f(self, *args, **kwargs)
  File "/opt/CAPEv2/lib/cuckoo/core/database.py", line 2103, in get_tasks_status_count
    tasks_dict_count = session.query(Task.column, func.count(Task.column)).group_by(Task.column).all()
AttributeError: type object 'Task' has no attribute 'column'
```

**Comment by doomedraven** [comment]
in my case return is different 
```
>>> tasks_dict_count
[('reported', 6)]

```
@return: dict with status and number of tasks found example: {'failed_analysis': 2, 'running': 100, 'reported': 400}
```

sqlalchemy.__version__
'1.4.17' checked latest the same result 1.4.28

**Comment by doomedraven** [comment]
pushed fix, idk how it was returning your dictionary, but without wrap that with dict() it returns lit of tuples

**Pull request merged**
