### PR TITLE
remove six library

### PR DESCRIPTION
**Pull request by doomedraven**
still have to fix few things related to strings and unicode

### CODE REVIEW

**Comment by doomedraven** [comment]
@TheMythologist what do you think about the six removal changes?

**Comment by TheMythologist** [comment]
Sorry for the late reply, but it looks good. There are still a couple of other files that use six:

Search for `from six`, e.g. `from six.moves import zip`.
The three files are:
- modules/processing/usage.py
- modules/processing/parsers/CAPE/REvil.py
- utils/tcpdumpwrapper.py

**Comment by doomedraven** [comment]
Thanks, damn my grep didnt catch them, changing them

**Comment by doomedraven** [comment]
ok i was grepping for `import six`, not `from six` thanks

**Pull request merged**
