### PR TITLE
Add DarkGate payload dump and detection

### PR DESCRIPTION
**Pull request by enzok**

### CODE REVIEW

**Comment by kevoreilly** [comment]
Looks beautiful ❤️ 

Seems to have failed ruff due to `modules/processing/parsers/CAPE/DarkGate.py:33:5: F841 [*] Local variable `config_data` is assigned to but never used`

**Comment by kevoreilly** [comment]
Could always add a 'packed' example hash to the yara metadata, i.e.:

```
packed = "4bd54d05abeb59dcf2b4d1bf9dd51c26049a0d012da85ec8f93430751bf52050"
```

**Comment by kevoreilly** [comment]
Ooh and a changelog entry for this!

**Comment by kevoreilly** [comment]
So proud ❤️

**Comment by doomedraven** [comment]
and a test :)

**Pull request merged**
