### PR TITLE
Added: CSRF Protection

### PR DESCRIPTION
**Pull request by AndreaF17**
I had some problems during the submit of the files using dns-name:

With this code you can get rid of the CSRF error if you set the allowed hostname in `CAPEv2/config/web.conf` as follows:
```
# hostname of the cape instance
hostname = https://example.com
```

I hope that helps

### CODE REVIEW

**Comment by doomedraven** [comment]
Thanks this is useful, but should go into settings and not local, can you move it? Local is for overwrite/extend settings. Py

**Comment by AndreaF17** [comment]
Yes, no worries. I'm going to do it!

**Comment by AndreaF17** [comment]
That should be it!

**Comment by doomedraven** [comment]
thank you

**Pull request merged**
