### PR TITLE
Fix Task.tags has no is_.

### PR DESCRIPTION
**Pull request by N1neSun**
Task.tags is sqlalchemy relationship object which has no function is_().

### CODE REVIEW

**Comment by doomedraven** [comment]
hm from my last test `is` wasn't working to check if that was None, i had to use `==`, going to check that again with is or ==

**Comment by doomedraven** [comment]
hm which version of sqlalchemy do you use? i do see `is_`, or is something else?
```
>>> dir(Task.tags)
'is_', 'is_aliased_class', 'is_attribute', 'is_bundle', 'is_clause_element', 'is_distinct_from', 'is_instance', 'is_mapper', 'is_not', 'is_not_distinct_from', 'is_property', 'is_selectable', 'isnot',
```

**Comment by doomedraven** [comment]
or you referring to this?

```
>>> Task.tags.is_(None)
Traceback (most recent call last):                                                                                                                                                                                 
  File "<stdin>", line 1, in <module>                                                                                                                                                                              
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/operators.py", line 688, in is_                                                                                                                     
    return self.operate(is_, other)                                                                                                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/attributes.py", line 316, in operate                                                                                                                
    return op(self.comparator, *other, **kwargs)                                                                                                                                                                  
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/operators.py", line 1337, in is_                                                                                                                     
    return a.is_(b)                                                                                                                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/operators.py", line 688, in is_                                                                                                                     
    return self.operate(is_, other)                                                                                                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/operators.py", line 225, in operate                                                                                                                 
    raise NotImplementedError(str(op))                                                                                                                                                                             
NotImplementedError: <function is_ at 0x7faf00a67ca0>
```

**Comment by N1neSun** [comment]
> or you referring to this?
> 
> 
> 
> ```
> 
> >>> Task.tags.is_(None)
> 
> Traceback (most recent call last):                                                                                                                                                                                 
> 
>   File "<stdin>", line 1, in <module>                                                                                                                                                                              
> 
>   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/operators.py", line 688, in is_                                                                                                                     
> 
>     return self.operate(is_, other)                                                                                                                                                                                
> 
>   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/attributes.py", line 316, in operate                                                                                                                
> 
>     return op(self.comparator, *other, **kwargs)                                                                                                                                                                  
> 
>   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/operators.py", line 1337, in is_                                                                                                                     
> 
>     return a.is_(b)                                                                                                                                                                                                
> 
>   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/operators.py", line 688, in is_                                                                                                                     
> 
>     return self.operate(is_, other)                                                                                                                                                                               
> 
>   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/operators.py", line 225, in operate                                                                                                                 
> 
>     raise NotImplementedError(str(op))                                                                                                                                                                             
> 
> NotImplementedError: <function is_ at 0x7faf00a67ca0>
> 
> ```

Yes，i referring this.

**Comment by N1neSun** [comment]
> hm from my last test `is` wasn't working to check if that was None, i had to use `==`, going to check that again with is or ==

I'm sorry,I only noticed the errors,did not notice if it working will.I will check that.

**Comment by doomedraven** [comment]
thats is interesting, anyway i think we can remove that last part of condition as that was added for start of migration and if you have current tasks without tags, but since we added arch field is already some time passed so im gonna remove it

**Comment by N1neSun** [comment]
> thats is interesting, anyway i think we can remove that last part of condition as that was added for start of migration and if you have current tasks without tags, but since we added arch field is already some time passed so im gonna remove it

I think so.

**Comment by doomedraven** [comment]
thank you, i will check another pr a bit later

**Comment by N1neSun** [comment]
That's ok.Happy new year for being late btw!

**Comment by doomedraven** [comment]
happy new year to you too :)

**Pull request merged**
