### PR TITLE
View remote session from status.html page

### PR DESCRIPTION
**Pull request by CarsonHrusovsky**
This change allows viewing the remote session from the status page as well. This is useful when submitting via API for example as the initial remote session button won't be accessible.

### CODE REVIEW

**Comment by doomedraven** [comment]
hey, thanks, i have to improve that as for those who doesn't use guacamole they don't need to see that + there is a bug in html code, url `here` is broken

**Comment by CarsonHrusovsky** [comment]
Sounds good doomed

**Comment by doomedraven** [comment]
can you plz check my changes when you have oportunity?

**Comment by CarsonHrusovsky** [comment]
I can look into this next week for testing - I will be away from keyboard for a bit.

**Comment by doomedraven** [comment]
merged to staging for a week

**Pull request merged**
