### PR TITLE
Adding note about archive usage

### PR DESCRIPTION
**Pull request by cccs-kevin**
I've made a few talks recently regarding the increased presence of non-zip archive files being used by malicious actors in present day. My work on the `archive.py` package provides CAPE's best chance of detecting these samples and network IOCs. This note is to assist those who are using a client to submit files to CAPE that is not [Assemblyline ](https://cyber.gc.ca/en/tools-services/assemblyline).

### CODE REVIEW

**Comment by doomedraven** [comment]
thank you for your work on it

**Comment by cccs-kevin** [comment]
For those interested, here is one of such talks: https://www.youtube.com/watch?v=-70Mlkmtdds&t=11056s

**Comment by doomedraven** [comment]
nice talk, i did quick look skipping some parts. but i think your explanation of archive package would be probably even nice to link to docs so newcomers could use that. what do you think?

**Comment by doomedraven** [comment]
;) https://github.com/kevoreilly/CAPEv2/commit/54083aa71543c0923ea6f96102bb7ff3157d8ed4

**Comment by doomedraven** [comment]
linked in docs too https://capev2.readthedocs.io/en/latest/usage/packages.html

**Pull request merged**
