### PR TITLE
Fix unpack child filename bugs

### PR DESCRIPTION
**Pull request by N1neSun**
rar,eml and so on  which has included files may cause the bug, because some filename may have unicode string。I was try to solve the unicode problems, but it's not easy.I will try my best.

### CODE REVIEW

**Comment by doomedraven** [comment]
thanks, do you have hash to test?

**Comment by N1neSun** [comment]
> thanks, do you have hash to test?

test this function？I tested locally.

**Comment by doomedraven** [comment]
yes but my devops might ask for hash to have proper test

**Comment by N1neSun** [comment]
What do I need to do?

**Comment by doomedraven** [comment]
give me a hash/file that i can pass to my devops

**Comment by N1neSun** [comment]
f2d87361b01a4419d295f9b695527cf0aeb0fe40e43ab26445fa6c90a2b93ece, this hash in virustotal can complete the test.

**Comment by N1neSun** [comment]
[test.zip](https://github.com/kevoreilly/CAPEv2/files/7788107/test.zip)
sorry，I just tried the above hash but it doesn’t work. Here is a file for testing.

**Comment by doomedraven** [comment]
thanks i was able to test that

**Comment by N1neSun** [comment]
I'm very sorry, I think there may be another bug that has not been resolved, I will submit another pr.

**Comment by doomedraven** [comment]
Thanks i saw bug in sflock to handle that error i already have fix

**Comment by N1neSun** [comment]
nice

**Comment by doomedraven** [comment]
I will push in a bit

**Comment by N1neSun** [comment]
Ok,have a nice day!

**Comment by doomedraven** [comment]
thank you, you too

**Pull request merged**
