### PR TITLE
update Blister Loader yara rule

### PR DESCRIPTION
**Pull request by r0ny123**

### CODE REVIEW

**Comment by kevoreilly** [comment]
Thank you

**Comment by doomedraven** [comment]
this yara doens't match specified sample

**Comment by kevoreilly** [comment]
Reasons for rejection:

- yara didn't match sample
- two original patterns still exist in modified form but unaltered
- one of two new patterns applies to old sample (unnecessary)
- other new pattern is the only pattern to detect new sample, so signature would become effectively a single pattern

**Comment by r0ny123** [comment]
> yara didn't match sample

Partially correct. 
The mentioned sample did match the string `$xor_dec_new` (which was my intention), the problem was with the condition `2 of them`, which was why the yara didn't match. Only two of those XOR variants found ITW. I would like to have those XOR-based hex strings in YARA.

**Pull request closed without merging**
