### PR TITLE
Use yaramod to format yara rules

### PR DESCRIPTION
**Pull request by r0ny123**
Here is the result: https://github.com/r0ny123/CAPEv2/commit/61cbe01daa053a77dd8d380ce2fe10c00234f11f

Also, @doomedraven can you rename the branch name `master` to `main`? Please rename before merging this PR.

### CODE REVIEW

**Comment by doomedraven** [comment]
Im not admin of the repo, only kevin has those permissions

**Comment by TheMythologist** [comment]
If you're renaming to main could you edit the other workflows to point to the correct branch as well

**Comment by kevoreilly** [comment]
What's renaming the branch got to do with yara sigs?

**Comment by doomedraven** [comment]
that is due to WOKE culture xD

**Comment by r0ny123** [comment]
> If you're renaming to main could you edit the other workflows to point to the correct branch as well

Yup, @TheMythologist, I can do that. But @doomedraven got the point. :D

**Comment by kevoreilly** [comment]
Renaming the branch is not relevant to the PR

**Comment by r0ny123** [comment]
I am not sure I understand what are you saying, but changing the name isn't that hard. Anyway, updating the PR.

**Comment by kevoreilly** [comment]
My language is clear. This PR has to do with yara, therefore it is not the place to request (or demand) a change to the branch.

**Comment by kevoreilly** [comment]
I am not a fan of spaces after opening brackets either.

**Comment by doomedraven** [comment]
so till they won't add formatting configuration is a dead end. https://yaramod.readthedocs.io/en/latest/formatting_rulesets.html
i don't really like the output that it generates

**Comment by r0ny123** [comment]
Ok I will check thr suggestions with the author.

**Pull request closed without merging**
