### PR TITLE
Enhancement: WHOIS Lookup of Domains Contacted By Malware

### PR DESCRIPTION
**Pull request by goheesheng**
Files Added/Changed

1) 
In /opt/CAPEv2/modules/processing/network.py

photo_6269093690588903133_y

Modified this processing module to add a function to query the WHOIS API and obtain the JSON output containing domain information.

2) 
In /opt/CAPEv2/conf/processing.conf
photo_6269093690588903134_x

Added the necessary configuration fields for /opt/CAPEv2/modules/processing/network.py to obtain the WHOISXML Account API Key and query the WHOIS API for domain information.
Fill “whois_query” with yes/no depending on whether you want WHOIS query to be enabled/disabled, and fill “whois_apikey” with the API key copied earlier.

3) 
/opt/CAPEv2/web/templates/analysis/network/_whois_hosts.html
/opt/CAPEv2/web/templates/analysis/network/_whois_hosts_not_ajax.html
Added HTML templates to display the domain information obtained from WHOISXML API in a table format.

photo_6269093690588903135_y

photo_6269093690588903136_y

4) 
/opt/CAPEv2/web/templates/analysis/overview/index.html
/opt/CAPEv2/web/templates/analysis/network/index.html
Added “includes” section in both index files to include the _whois_hosts.html and _whois_hosts_not_ajax.html files in the template.
photo_6269093690588903137_y

Steps to set up WHOISXMLAPI Account
*** For a free account, there is a one-time limit of only 500 WHOIS API Requests.

3) Sign up for a WHOISXML API Account at https://main.whoisxmlapi.com/signup. 
photo_6269093690588903130_y

4) Enter the relevant information and click on “Sign Up”
*** Use an actual email address as the sign up process requires email verification
photo_6269093690588903132_y

5) Upon receiving the verification email, click on the account activation link:

6)**Navigate to https://user.whoisxmlapi.com/products and copy your API Key. It will be needed later on in the CAPEv2 configuration file.**

### CODE REVIEW

**Comment by doomedraven** [comment]
Hello please start making a proper pull requests, nobody will review 132 not related files. instead of posting link to path and image in comments. you could post path and markdown escaped code. as otherwise till you fix all those PR they will be pending for your correction

**Comment by goheesheng** [comment]
I have removed unrelated files

**Comment by doomedraven** [comment]
thank you, could you review network.py as you removing/restoring to old code. once that done we are fine to go i think

**Comment by goheesheng** [comment]
@doomedraven I have edited it, thanks

**Comment by doomedraven** [comment]
thanks, im receiving emails about each commit so i see everything

**Comment by doomedraven** [comment]
you have 

```
Run # stop the build if there are Python syntax errors or undefined names
./modules/processing/network.py:112:8: E999 IndentationError: unexpected indent
        for domain in f.splitlines():
       ^
1     E999 IndentationError: unexpected indent
1
Error: Process completed with exit code 1.
```

**Comment by doomedraven** [comment]
if you need both you can keep append it as {raw:result, parsed{x:y}}

**Comment by doomedraven** [comment]
So im fine to merge this once html code will be properl, i don't want any parsing on django side, they should be done on server side. in case if you want plan to update it, just close this PR

**Comment by doomedraven** [comment]
Amazing thank you for wasting my time on your code

**Comment by goheesheng** [comment]
> Amazing thank you for wasting my time on your code

I thought you pushed this to community?

**Comment by goheesheng** [comment]
May I ask why did you edited the externalservices.conf that way?

```lib/cuckoo/common/integration/whoisxml.py
import logging

import requests
from lib.cuckoo.common.config import Config

log = logging.getLogger()
externalservices_cfg = Config("externalservices")
apikey = externalservices_cfg.whoisxmlapi.apikey


def whoisxmlapi_lookup(host):
    if not externalservices_cfg.whoisxmlapi.enabled or not apikey:
        return {}

    result = {}
    log.debug("Performing WHOIS Query for IP/Domain: %s", host)
    url = f"https://www.whoisxmlapi.com/whoisserver/WhoisService?apiKey={apikey}&domainName={host}&outputFormat=json"
    try:
        r = requests.get(url, verify=False)
        if r.ok:
            result = r.json()
    except Exception as e:
        log.error("whoismlapi.com exception: %s", str(e))

    return result
```

```conf/externalservices.conf
[misp]
enabled = no
url =
apikey =
hash_lookup = no

```

**Comment by doomedraven** [comment]
if you close without comments that means that you abondone your work.
config modified in that way because we don't need that as part of networking, is external service, so it should be in that file.

about community, in community is all code that is not maintained by core devs, but is autointegrable by running `utils/community.py -waf`

will you rewrite the html code? bear in mind that storing the whole json to mongo, if there are lot of data for many hosts, it might reach limit of 16mb and mongo can remove it, so better add parsed data and option to store raw on disk

**Comment by goheesheng** [comment]
so when we test it our work, we use conf/externalservices.conf?

I am confused with touching that since that is for misp and not whois. Do I edit conf/externalservices.conf or create a new one?

**Comment by doomedraven** [comment]
you probaably working againon old code. in this PR there is nothing related to that config, the config is itself in repo with misp and whois https://github.com/kevoreilly/CAPEv2/blob/master/conf/externalservices.conf

**Comment by goheesheng** [comment]
My fellow colleague will complete my work, thus I will close this PR

**Comment by Dylan818** [comment]
Hi, I am the colleague that will take over Eesheng's work, may I know what is needed to be followed up on and changed?

**Comment by doomedraven** [comment]
please read the whole thread to see all my replays that contains examples

**Comment by Dylan818** [comment]
Hi, so can I confirm that the improvements needed are as follows?

1) Parsing whois data (dictionary) on server side and not n django
2) Edit HTML code to support that

**Comment by Dylan818** [comment]
Hi, are there any updates on this? Thank you!

**Comment by doomedraven** [comment]
totally missed this one, those templates only exist in this PR, yes parsing in django is awful and bad. everything should be done on server side

**Pull request closed without merging**
