### PR TITLE
Update plugins.py

### PR DESCRIPTION
**Pull request by firmianay**
'family' seems like a redundant variable

### CODE REVIEW

**Comment by doomedraven** [comment]
is what i had tried yesterday, but that isnot optimal solution https://github.com/kevoreilly/CAPEv2/commit/b66810ef22e24c5f39f42448ce40ec27a7fc6458, the idea is to not check the rest once it detected, and it going from more trusted "software" to lowest, as if we remove if not family it will enter each section and we don't want that, but thank you for your time :)

**Comment by firmianay** [comment]
But now it also enter each section if `self.results.get("detections", False)` returns False. So I think `if not family` is useless.

**Comment by doomedraven** [comment]
it should enter each section, if cape detection is empty, as it works as:
```
If CAPE
elif suricata
elif VT
elif ClamAV
```

that is our detection way to try to get malfamily by that software/services

**Comment by doomedraven** [comment]
the thing here, is we check family,bcz it can not set, imagine that what that service detects, is blacklisted and family keeps empty, is why we walk that way, but if you have improvement idea is more than welcome

**Comment by firmianay** [comment]
ok if you want to keep this control flow structure.

**Pull request closed without merging**
