### PR TITLE
Fix: Zipped files defaults to windows platform

### PR DESCRIPTION
**Pull request by kenleejl**
When submitting a zipped elf file, it goes to the windows platform. This fix will return the platform accordingly

### CODE REVIEW

**Comment by doomedraven** [comment]
hello interesting, i think we should probably change that to set file - platform relation not only all files and platform, as if you submit different fileformats it will still be a problem

**Comment by para0x0dise** [comment]
@kenleejl 
I have the same issue when submitting a python file, it goes to Linux platform

**Comment by doomedraven** [comment]
this is not proper implementation as you add platform only in one place to return, that will fail on other returns. i have properly implemented this here https://github.com/kevoreilly/CAPEv2/pull/1701 should be merged on Wednesday, thanks guys for headups about this issue

**Comment by doomedraven** [comment]
merged to master now

**Pull request closed without merging**
