### PR TITLE
Enable packet forwarding for IPv4

### PR DESCRIPTION
**Pull request by qux-bbb**
Always need to enable ip forwarding, so put it in the installation script.

### CODE REVIEW

**Comment by doomedraven** [comment]
never need to enable it. rooter does that for you. why just not to use it?

**Comment by qux-bbb** [comment]
If you do not enable IP forwarding, rooter is invalid.  
In documentation:  
https://capev2.readthedocs.io/en/latest/installation/host/routing.html#using-per-analysis-network-routing  
```r
Both global routing and per-analysis routing require ip forwarding to be enabled:
echo 1 | sudo tee -a /proc/sys/net/ipv4/ip_forward
```

What I did was add it to the installation script.

**Comment by doomedraven** [comment]
ok you are right, i confused with another option, my bad

**Comment by qux-bbb** [comment]
My bad description. Thank you for the merge.

**Pull request merged**
