### PR TITLE
Introduced Google Backup Feature

### PR DESCRIPTION
**Pull request by goheesheng**
Files Added/Changed
With the MISP Docker instance set up, the following files were changed to extract the threat intelligence from MISP into CAPEv2 for threat attribution

1)
In /opt/CAPEv2/modules/processing/targetinfo.py

photo_6269093690588903125_x

Added a compare_to_misp function in this existing file which collects information about the submitted sample. The function was added here as it requires the SHA256 hash to query MISP, and targetinfo.py is the script that obtains the different hashes of the submitted sample.

2) 
In /opt/CAPEv2/utils/<name_of_credentials_file>.json
In our setup, we named the credentials file fypj.json. It contains the data needed for connection to the Google Service Account.

Screenshot 2023-02-06 151513

3) In /opt/CAPEv2/conf/reporting.conf
Screenshot 2023-02-06 151611

Added the necessary configuration fields for /opt/CAPEv2/modules/reporting/reportbackup.py to obtain the Google Service Account Credentials (should be a JSON file) and upload the reports to the specified folder (provide the Folder ID).
Fill “credentials_location” with the name of the JSON key file (which should be moved to /opt/CAPEv2/utils”. Fill “folder_id” with the folder ID. If everything is configured correctly, then the Google Drive Shared Folder will be populated with the analysis reports named “report<analysis number>.<report format>”:

photo_6269093690588903129_w

### CODE REVIEW

**Comment by doomedraven** [comment]
Thank you, but this PR includes the memory feature from another PRs, i can't merge or start working on that till you solve this problem

**Comment by doomedraven** [comment]
acording to you there is 3 files changed, but in your PR there is 131

**Comment by goheesheng** [comment]
There was a lot of changes in my PR because I update my files from your repo

**Comment by doomedraven** [comment]
well when you update from main repo, number of changes decreases due to less changes. 

But here we have for example google backup reporting module + html files that re not related to the PR, and the similar situation  is in each PR. Can you fix it?

**Comment by doomedraven** [comment]
+ things liek those should be pushed to https://github.com/kevoreilly/community as is community features and won't be maintained by lead devs

also as point 1 you speak about misp which is not related to this one neither, that confusing

**Comment by goheesheng** [comment]
I have removed unrelated files

**Comment by doomedraven** [comment]
Few notes here.
1. do not use f-strings for logging, it has performance impact, you can search that discussion in issues
2. CWD is not utils, is `/opt/CAPEv2`.
3. When you add new module, use HAVE_X + try/except to properly handle it for the rest of the user, check out my commit with those changes
4. Don't use your related stuff like `fypj`, `fypj.json` says literally nothing to others users.
5. i did it more generic, in case someone wants to add some other service. as ` report backup` is not the same as `report backup to google drive`

check it please and let me know

**Comment by doomedraven** [comment]
thanks

**Comment by goheesheng** [comment]
Thanks for your help!

**Comment by doomedraven** [comment]
you are welcome

**Comment by kevoreilly** [comment]
Thanks for your contribution, much appreciated.

**Pull request merged**
