### PR TITLE
Adding the ability to extract an archive (ISO, VHD, etc) into a folder and run an executable

### PR DESCRIPTION
**Pull request by cccs-kevin**
Tested with a few ISO and VHD files and it works pretty well. You need 7-zip installed on your guest machines.

### CODE REVIEW

**Comment by doomedraven** [comment]
there was in past zip.py that was doing the same, i personally prefer to move that to sflock as otherwise you lose relationship  between archive and childs

**Comment by cccs-kevin** [comment]
> there was in past zip.py that was doing the same, i personally prefer to move that to sflock as otherwise you lose relationship between archive and childs

In what way is the relationship lost? The archive file is uploaded and a new folder is created with the same base name of the archive, and the children are extracted into that folder.

**Comment by kevoreilly** [comment]
Thanks for this PR.

I just tried it but unfortunately it crashed:

```
2022-09-06 14:02:24,763 [root] INFO: You probably submitted the job with wrong package
Traceback (most recent call last):
  File "C:\tmpljosyc8h\analyzer.py", line 528, in run
    pids = self.package.start(self.target)
  File "C:\tmpljosyc8h\modules\packages\archive.py", line 139, in start
    os.mkdir(root)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Rebecca\\AppData\\Local\\Temp\\1fc7b0e1054d54ce8f1de0cc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\tmpljosyc8h\analyzer.py", line 1397, in <module>
    success = analyzer.run()
  File "C:\tmpljosyc8h\analyzer.py", line 534, in run
    raise CuckooError(f'The package "{package_name}" start function encountered an unhandled exception: {e}') from e
lib.common.exceptions.CuckooError: The package "modules.packages.archive" start function encountered an unhandled exception: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Rebecca\\AppData\\Local\\Temp\\1fc7b0e1054d54ce8f1de0cc'
```

Hopefully simple to fix.

**Comment by cccs-kevin** [comment]
I'll test it out and report back

**Comment by cccs-kevin** [comment]
Works fine for me... Are you using the most updated [`archive` package](https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/modules/packages/archive.py)? Also question, is your submitted sample named `1fc7b0e1054d54ce8f1de0cc95976081c7a85c7926c03172a3ddaa672690042c` or is it renamed to `1fc7b0e1054d54ce8f1de0cc95976081c7a85c7926c03172a3ddaa672690042c.iso`?

**Comment by kevoreilly** [comment]
It would be nice to have the possibility of putting 7z.exe in analyzer/windows/bin instead of needing to have it baked into the vm image...

**Comment by cccs-kevin** [comment]
> I am using the most up-to-date package, but did not rename the iso - if I do I see this is no longer an issue.

Let me know if [this PR](https://github.com/kevoreilly/CAPEv2/pull/1132) works without the renaming.

**Comment by cccs-kevin** [comment]
> It would be nice to have the possibility of putting 7z.exe in analyzer/windows/bin instead of needing to have it baked into the vm image...

https://github.com/kevoreilly/CAPEv2/pull/1133

**Pull request merged**
