### PR TITLE
Deprecate OlympicDestroyer sig due to FP on Cryptbot

### PR DESCRIPTION
**Pull request by r0ny123**
eg. https://capesandbox.com/analysis/111175/

### CODE REVIEW

**Comment by doomedraven** [comment]
thanks

**Comment by doomedraven** [comment]
now you need to create account on public sandbox

**Comment by r0ny123** [comment]
> 
> 
> now you need to create account on public sandbox

Yeah already did :) and decision is well taken ;)

**Comment by doomedraven** [comment]
great

**Pull request merged**
