### PR TITLE
Processing Improvements

### PR DESCRIPTION
**Pull request by cccs-kevin**
- Configurable behaviour sub-modules
- Bugfix for `add_error` call
- Updating behaviour signature processing to be in-line with how Cuckoo does it
- Add `web_reporting` config to allow both mongodb and elasticsearch reporting to be disabled. This is useful for when you want the REST API that Django supplies, but you don't want the GUI.
- Adding `rtmp` default value
- Toggle the use of `list(process["calls"])` since it is only useful for certain reporting modules, like mongodb.
- Adding check if file exists for PE-parsing
- Adding a `finally` statement in the scheduler from Cuckoo that marks tasks as completed if there is an AnalysisManager error.
- Fixing ramboost bug
- Adding `matched` attribute to the `Signature` class to avoid duplication of signature hits
- Adding check for if sample doesn't exists in db

Something that I have noticed in CAPE which I don't think(?) was an issue in Cuckoo, is the length of time that it takes to iterate through the `calls` of a process here https://github.com/kevoreilly/CAPEv2/blob/1822c2ed8700548878dbedd6c676bb403e478961/lib/cuckoo/core/plugins.py#L494

For instance, I have a sample (a batch file with one line `start "" https://www.stackoverflow.com`) that creates a process which opens `iexplore.exe`. This process makes a lot of calls. Without `ramboost` turned on, the processing of the Bson logs in the `behavior.py` module takes ~2 seconds, and then the iteration of calls when applying evented signatures takes ~30 seconds (even with my improvements in this PR). When I turn `ramboost` on, the processing of the Bson logs takes ~30 seconds and the signatures take ~2 seconds. So basically it always takes 32 seconds, which _feels_ like that is too long to just parse/iterate through logs. Is this issue something that people are aware of / can duplicate?

### CODE REVIEW

**Comment by doomedraven** [comment]
btw let me know once is ready to merge

**Comment by cccs-kevin** [comment]
> btw let me know once is ready to merge

Sure thing, there are still a few more things I want to do

**Comment by doomedraven** [comment]
Question about try excepto of file not found, whould t it be better to just use if os path exist?

**Comment by cccs-kevin** [comment]
> Question about try excepto of file not found, whould t it be better to just use if os path exist?

Yes, I'll update

**Comment by doomedraven** [comment]
Thanks

**Comment by doomedraven** [comment]
amazing work Kevin. thank you.

About ram_boost, that is feature from cuckoo-modified i think, maybe cuckoo has it, it already ages since i last checked cuckoo code. I have that off on all my servers. I will create issue for this to review once i finish huge RE  that i have on my table

**Comment by doomedraven** [comment]
something is broken, it says all my vms are dead after merge, investigating

**Comment by doomedraven** [comment]
ok nevermind, for some reason qemu disappeared from my server %)

**Comment by cccs-kevin** [comment]
> amazing work Kevin. thank you.
> 
> About ram_boost, that is feature from cuckoo-modified i think, maybe cuckoo has it, it already ages since i last checked cuckoo code. I have that off on all my servers. I will create issue for this to review once i finish huge RE that i have on my table

The issue that I'm talking about isn't even really about `ramboost`, it's about how long it takes to iterate through the ParseProcessLog object https://github.com/kevoreilly/CAPEv2/blob/200a80818f82f5b9487e9242f8da32ae969aa27c/modules/processing/behavior.py#L38

**Comment by doomedraven** [comment]
once i will have some spare time i will try to investigate it i have created issue to not forget about it https://github.com/kevoreilly/CAPEv2/issues/1024

**Pull request merged**
