### PR TITLE
Azure safety updates

### PR DESCRIPTION
**Pull request by ChrisThibodeaux**
Updates to handle critical errors when:
- Non-persistent machine deletion from the DB leads to a machine scheduled for deletion being assigned a task
- A machine's agent will sometimes be unreachable at startup
- A machine is sometimes added more than once to `delete_vm_list`
- On startup, an existing VM is on the VMSS
- On startup, a machine that was previously in the DB is still present on the VMSS
- On startup, when all initialized machines fail, add a configurable retry capability
- On startup, an existing VM is `locked`

Many of the changes are to make the code more thread-safe.
Delay monitor thread start to allow all VMSSs to be up and instances running, especially in the case of initial startup failures.

### CODE REVIEW

**Comment by doomedraven** [comment]
Hello, thank you, i will need first move this to staging before it will be merged to master to ensure that we didn't break nothing

**Comment by ChrisThibodeaux** [comment]
@doomedraven  Sounds good. I want to test it significantly on my end before moving forward with it as well. Is it possible to change this to a draft instead of a regular PR?

**Comment by doomedraven** [comment]
yes then draft would be good

**Comment by ChrisThibodeaux** [comment]
@cccs-mog If you have a chance to test this on your end, it should fix all the errors we discussed in #2323

**Comment by ChrisThibodeaux** [comment]
@doomedraven I removed the changes in `scheduler.py` and `abstracts.py`. Only `machinery/az.py` has changes to it now.

Ready to move out of draft now.

**Comment by doomedraven** [comment]
cool thank you, lets see if @cccs-mog can confirm it and then we fine to merge

**Comment by doomedraven** [comment]
i changed from staging to master as changes are only to az.py, so they are not so dangerous for the rest of users and easier to review

**Comment by cccs-mog** [comment]
Hi @doomedraven and @ChrisThibodeaux, I will take a look today and get back. Awesome work !

**Review by cccs-mog — COMMENTED** [review]
Awesome ! Seem to work wonders ! Only missing subnet limits and quota from https://github.com/kevoreilly/CAPEv2/pull/2291 :) Thanks a lot !

**Comment by doomedraven** [comment]
ok lets merge this then, and then someone use uses azure can add subnet limit and quota . thank you @ChrisThibodeaux for your work

**Pull request merged**
