### PR TITLE
Update startup.py

### PR DESCRIPTION
**Pull request by firmianay**

### CODE REVIEW

**Comment by doomedraven** [comment]
btw https://github.com/kevoreilly/CAPEv2/commit/50735e1bbfcac10f6dc6ec8ac1ddad93ba31247f ;)

**Comment by firmianay** [comment]
oh haha, thanks

**Comment by doomedraven** [comment]
thanks you for all the improvements, many parts of the code wasn't touched for more than 5y for sure

**Comment by kevoreilly** [comment]
Yes I too have been much admiring and appreciating these improvements :-)

**Pull request merged**
