### PR TITLE
Added info for error when set clock not succesful. Feature to ability monitor traffic between cape result server and sandbox.

### PR DESCRIPTION
**Pull request by piolug93**

### CODE REVIEW

**Comment by doomedraven** [comment]
why do you set VMs in NAT if docs says hostonly?

**Comment by doomedraven** [comment]
did you set that interface somewhere else? https://github.com/kevoreilly/CAPEv2/blob/master/modules/auxiliary/sniffer.py#L58C9-L58C76

**Comment by piolug93** [comment]
Machine have set hostonly interface. I change behavior of rooter. Because i must identifing traffic from sandboxes per sandbox on my network monitoring.

**Comment by piolug93** [comment]
I see that you closed the pull request without merging. Do you need any additional information about this functionality ?

**Comment by doomedraven** [comment]
what we close? this PR was closed by you

**Comment by piolug93** [comment]
Actually I don't know how it happened, sorry :)  I will create a new pull request. Suspicion falls on new changes introduced and force push

**Pull request closed without merging**
