### PR TITLE
Set maxsplit in `.split` and `.rsplit`

### PR DESCRIPTION
**Pull request by TheMythologist**
Small improvement in code by setting limit on `maxsplit`.
`.split` was changed to `.rsplit` in cases where only the last element was needed.

Unlike the other PRs, I have not individually reviewed these changes yet (as it's 1am in my timezone right now lol), I'll comment again when I've reviewed the changes myself (or if you want to you can review them too :D)

### CODE REVIEW

**Comment by doomedraven** [comment]
it looks good, but maybe that is just confusion, you added `maxsplit`, then removed anothers, and on the rest you don't use it

**Comment by TheMythologist** [comment]
I've looked through the commit and I think it's ready to be merged.

To avoid confusion, I used `.split(maxsplit=1)` when the `sep` argument is not passed into `.split` (i.e. it is splitting over any whitespace character).
In situations where the `sep` argument is already specified, I removed explicitly stating the `maxsplit` argument, and instead simply use `.split(".", 1)` as 1 will automatically be the `maxsplit` parameter.

**Comment by kevoreilly** [comment]
Ready to be merged needs actual testing - there have been a lot of bugs recently due to lack of this, review or looking are not enough.

**Comment by doomedraven** [comment]
ah nice, make sense @TheMythologist

**Comment by TheMythologist** [comment]
I have applied the changes to my local CAPE instance and everything is running as per usual.

**Comment by kevoreilly** [comment]
That is good - thanks for clarifying. If you could try and exercise the code that would be great.

I hope I don't appear ungrateful - I do appreciate all the code cleanup you have contributed recently.

**Comment by TheMythologist** [comment]
Sorry but what do you mean by exercise the code?

Also no worries, I'm aware that creating such massive PRs is a headache for both of us.

**Comment by kevoreilly** [comment]
I simply mean to execute the code that has changed with sufficiently variable input to test that it does not crash and works properly. I suggest this as it may not be sufficient to just 'run cape as usual' to get the code that has changed to be executed. Like fuzzing, good testing needs code coverage.

**Pull request merged**
