### PR TITLE
Update rat_dcrat.py

### PR DESCRIPTION
**Pull request by ditekshen**

### CODE REVIEW

**Comment by doomedraven** [comment]
thank you

**Comment by doomedraven** [comment]
btw not sure if you noted but when you pushing different PRs, they are all in the same latest pull request

**Comment by ditekshen** [comment]
I saw that but wasn't sure why. I'll do more reading on this

**Comment by doomedraven** [comment]
not sure, but maybe bcz when you creating PR, you pushing to master and then pull request? you can change name from master to something else, but that just headups, as that doesn't hurt nothing at all :)

**Pull request merged**
