### PR TITLE
Fix process log

### PR DESCRIPTION
**Pull request by qux-bbb**
I found that the process.log doesn't have log, and each task's log such as process-123.log doesn't have log.  
Now I know the process.log should have log. The autoprocess has "log.info", but the message cannot be logged.    
It's normal that the process-123.log doesn't have log, because there is no "log.info" in process func.  

I fix this bug by separating init_logging func.

### CODE REVIEW

**Comment by doomedraven** [comment]
thanks, i will check this on tuesday

**Comment by qux-bbb** [comment]
Is there any problem?

**Comment by doomedraven** [comment]
lack of time

**Comment by doomedraven** [comment]
sorry for delay, had another priorities to handle first.

the log is done to be in logs or in analysis folder
```
if logconf.logger.process_analysis_folder:
            path = os.path.join(CUCKOO_ROOT, "storage", "analyses", str(tid), "process.log")
        else:
            path = os.path.join(CUCKOO_ROOT, "log", "process-%s.log" % str(tid))
```

you neither has it there? as it works for me just fine

**Comment by qux-bbb** [comment]
> sorry for delay, had another priorities to handle first.
> 
> the log is done to be in logs or in analysis folder
> 
> ```
> if logconf.logger.process_analysis_folder:
>             path = os.path.join(CUCKOO_ROOT, "storage", "analyses", str(tid), "process.log")
>         else:
>             path = os.path.join(CUCKOO_ROOT, "log", "process-%s.log" % str(tid))
> ```
> 
> you neither has it there? as it works for me just fine

I have those codes， but there is a problem.  
Before my pr, the init_logging  func is invoked by process func, so the log before the process func will not write to the process.log file, such as `log.info("Processing analysis data")`, `log.info("Processing analysis data for Task #%d", task.id)`

**Comment by doomedraven** [comment]
thanks for more info, will check again in a bit

**Comment by qux-bbb** [comment]
> thanks for more info, will check again in a bit

If there is any question, please ask me.

**Comment by doomedraven** [comment]
there are no questions, there is lack of time so i must manage priorities, and this one must be tested, don-t forget we doing this in our free time, we have our jobs who pays our salaries, i know is small PR, but there some stuff that I must verify before, but sadly this weeks not that much time

**Comment by qux-bbb** [comment]
> there are no questions, there is lack of time so i must manage priorities, and this one must be tested, don-t forget we doing this in our free time, we have our jobs who pays our salaries, i know is small PR, but there some stuff that I must verify before, but sadly this weeks not that much time

Got it. I also do this in my free time. So please relax and do it later.

**Comment by doomedraven** [comment]
im relaxed lol, but as you push over and over i had to clarify you that is not our paid job. Trust me the latest thing that i want is to have PRs be on hold

**Comment by doomedraven** [comment]
thanks, sorry for delay

**Pull request merged**
