### PR TITLE
Updated docs

### PR DESCRIPTION
**Pull request by RazviOverflow**
I have updated the documentation in several sections. I tried to make the commits as self-explanatory as they get.

### CODE REVIEW

**Comment by RazviOverflow** [comment]
I think Github got desynchronized at some point. The 5 older commits (from Aug 7, 2022) have been already merged. Specifically: 

[Added documentation for guest's Python installation](https://github.com/kevoreilly/CAPEv2/pull/1079/commits/ba7e9177816e3124b0bba8cc5c85d888fd46d7ab)



[Added instructions to disable firewall and automatic update on Win 10](https://github.com/kevoreilly/CAPEv2/pull/1079/commits/fd2cb3e46618a42bb2a3553ff3d5be437d82d410)
 
[Supressed underlining too short](https://github.com/kevoreilly/CAPEv2/pull/1079/commits/90aaaaad68f7e9af21bdd006debb387284300561)


[Added instructions for setting a Static IP in Win10](https://github.com/kevoreilly/CAPEv2/pull/1079/commits/3b44499c7852eb7d0ab1dd291b8bbceef273055d)


[Merge branch 'kevoreilly:master' into master](https://github.com/kevoreilly/CAPEv2/pull/1079/commits/7bf21ab25cf58850d07c15ea24bde48d6709b6f5)

They are already part of CAPE main repo. 

I don't know what's going on.

**Comment by kevoreilly** [comment]
Wow thanks a lot!

**Comment by RazviOverflow** [comment]
> Wow thanks a lot!

You are most welcome! Given that I'm installing CAPE myself, I'll try to update the docs as much as I can so as to make the installation and usage of CAPE as friendly (and documented) as possible!

Do not hesitate to review all my commits and reach me out if there is any mistake. Both you and @doomedraven :)

**Comment by doomedraven** [comment]
thank you

**Pull request merged**
