### PR TITLE
Add dots for decimal separator

### PR DESCRIPTION
**Pull request by bartblaze**
A simple visibility / readability improvement. This is **not tested**, it should work, but would be great if someone can test!

_Example_
Will change
image

into:
image

### CODE REVIEW

**Comment by kevoreilly** [comment]
Hmm not sure if it's a country-specific thing but in the UK we do no use dots like that. That reads to me as four hundred and thirty nine point three zero four. Here we use commas for that. So the fact that it's not universal means I don't think we should adopt it.

If you are submitting PRs that are not tested, please use the staging branch not master!

**Comment by doomedraven** [comment]
it easier to read i agree, in Ukraine we neither use it. but still i do like it :P

**Comment by kevoreilly** [comment]
How about a comma instead of dot? Or maybe a space would be better.

**Comment by cccs-kevin** [comment]
> How about a comma instead of dot? Or maybe a space would be better.

I like the "space" suggestion. Commas are used in Canada for this sort of thing

**Comment by bartblaze** [comment]
Thanks for the feedback all! 😄 Spaces sound good, but not sure if Django can handle it just like that? Anyone has an idea?

**Comment by doomedraven** [comment]
django can do that with custom filter, will add that in near future

**Comment by nbargnesi** [comment]
> Thanks for the feedback all! 😄 Spaces sound good, but not sure if Django can handle it just like that? Anyone has an idea?

Use the l10n support in Django. I think we're at Django 4.2, so should just be a straightforward filter:

    {{ report.estimate_day | localize }}

Check out https://docs.djangoproject.com/en/4.2/topics/i18n/formatting/#std-templatefilter-localize.

Though by rough count, I see 157 templates. Localizing just one of them probably isn't ideal.

**Comment by bartblaze** [comment]
> > Thanks for the feedback all! 😄 Spaces sound good, but not sure if Django can handle it just like that? Anyone has an idea?
> 
> Use the l10n support in Django. I think we're at Django 4.2, so should just be a straightforward filter:
> 
> ```
> {{ report.estimate_day | localize }}
> ```
> 
> Check out https://docs.djangoproject.com/en/4.2/topics/i18n/formatting/#std-templatefilter-localize.
> 
> Though by rough count, I see 157 templates. Localizing just one of them probably isn't ideal.

Probs better to await @doomedraven's implementation / idea, depends on the preference 😄

**Comment by r0ny123** [comment]
> > How about a comma instead of dot? Or maybe a space would be better.
> 
> I like the "space" suggestion. Commas are used in Canada for this sort of thing

+1 for comma.

**Comment by doomedraven** [comment]
done, here is a good explanation how to handle that with coma or make it locale https://stackoverflow.com/questions/1823058/how-to-print-a-number-using-commas-as-thousands-separators/10742904#10742904

**Comment by doomedraven** [comment]
image

**Comment by doomedraven** [comment]
so i have put space as is more neutral and easier to read

**Comment by bartblaze** [comment]
Awesome 👍

**Pull request merged**
