### PR TITLE
Add AWS Deployment guide to README.md

### PR DESCRIPTION
**Pull request by Y4nush**
Hi, I noticed that there is no documentation on how to deploy to AWS, such as what you have for Azure. I have been working on a comprehensive guide that explains how to deploy CAPEv2 to AWS from scratch. I would appreciate it if you would agree to add it to the README or to another location in the repository. The source code of my website is available in that repository: https://github.com/Y4nush/y4nush.com.
Thank you!

### CODE REVIEW

**Comment by doomedraven** [comment]
FYI you not really to uncomment those, you only need to change ip/port if they are different from cuckoo.conf and tags shouldn't be empty or commented

```
Uncomment #options =
Uncomment #tags = and add tags = none
Uncomment # resultserver_ip = and add your server ip
Uncomment #resultserver_port = 2042
```

**Comment by doomedraven** [comment]
but so far, very good writeup for those who starts with CAPE on AWS

**Comment by Y4nush** [comment]
Hi, @doomedraven  sure! that's okay from my side. 
Thank you for the feedback. I will update the blog post accordingly.

**Comment by doomedraven** [comment]
cool thanks, i will show you PR once that is done before merge

**Comment by doomedraven** [comment]
why do you remove it?

**Comment by Y4nush** [comment]
> why do you remove it?

**Comment by Y4nush** [comment]
Hi @doomedraven, I did that accidentally while I opened the IMDS pull request.

By the way, I would like to edit the blog post based on the IMDS authentication method. I will update once I complete that. Is that okay from your side?

**Comment by Y4nush** [comment]
Hi @doomedraven, I have updated the blog post, thanks!

**Comment by doomedraven** [comment]
thanks for headups and documenting this

**Comment by doomedraven** [comment]
i still have to add aws setup docs https://y4nush.com/posts/installation-of-capev2-sandbox-on-aws/

**Pull request merged**
