### PR TITLE
Don't lose data when multiple configs for the same family are found.

### PR DESCRIPTION
**Pull request by tbeadle**
Keep them separate and maintain the file_obj hashes associated with each one.

### CODE REVIEW

**Comment by kevoreilly** [comment]
Hmm I'm not sure about this - currently the design is that if it's a single family name, the config should be merged non-destructively. If they need to be separated they should be classified differerently.

**Comment by tbeadle** [comment]
The problem we ran in to was that the original sample had a config extracted. Then a payload had a config extracted for the same family. Due to a bug in the extractor, it returned all empty strings for the fields that had been extracted from the sample, which led to data loss because those overwrote the original ones. That got me thinking that distinct configs should always just be stored separately, so that it looks like this: 
image
Note that this was taken after the bug in the config extractor was fixed and you'll notice that the payload does not have the Mutex field.

**Comment by doomedraven** [comment]
looks fine to me, but i will leave this to Kevin to decide

**Comment by kevoreilly** [comment]
This caters for what I perceive as a very unlikely scenario - two distinct variants from the same family with different configs in the same job. 

The issue I have is that what is a far more common scenario is that there are often multiple payloads from a single sample which may each contain the config. There are other scenarios where the whole config for a sample may be split across payloads. Finally there is the scenario in dynamic (debugger-based) config extraction where by its very nature it often involves capturing a single config item field in a dump, where the assumption is they will all be merged in the end.

It is for the above three scenarios that I had designed the current system of merging, and unfortunately to fix it for the scenario you mention of multiple variants in a single job seems to break the handling of the others which are far more common.

**Comment by doomedraven** [comment]
Self update, is frequent thing

**Comment by kevoreilly** [comment]
I am open to suggestions on how to handle all these cases concurrently. And although I'd be keen to keep it on by default, I would also be happy to make the merging a configurable option.

**Pull request closed without merging**
