### PR TITLE
Create Bokbot.yar

### PR DESCRIPTION
**Pull request by r0ny123**

### CODE REVIEW

**Comment by doomedraven** [comment]
thanks

**Comment by doomedraven** [comment]
FYI all yara rules that is written by community is moved to community repo

**Comment by r0ny123** [comment]
Thnaks!
what do you mean by core yara and community yara?

**Comment by doomedraven** [comment]
core yara, is done by @kevoreilly  or me, https://github.com/kevoreilly/community there is community stuff, so is that way we avoid to be responsable of FP, bad code, not maintained plugins that we don't use, so everyone can just remove them or do whatever they want on their side

**Comment by doomedraven** [comment]
as example you posted yara, that won't be shown in webgui due to missed correct type inside of cape_type, do search by `cape_type` in repo and you will see the difference

**Comment by r0ny123** [comment]
Thanks for the explanation!

**Comment by doomedraven** [comment]
You are welcome, thanks for yara

**Pull request merged**
