### PR TITLE
Git commit hooks

### PR DESCRIPTION
**Pull request by TheMythologist**
## Pre-commit hooks!
Currently has the following hooks:
1. Check yaml files for parseable syntax
2. Ensure that files are either empty or end with one newline
3. Trim trailing whitespace from all files
4. Remove utf-8 byte order marker
5. Replace mixed line ending
6. Run black
7. Run isort

To use the pre-commit hooks:
```bash
poetry install
poetry run pre-commit install
```

_Side note_: we need to update the the docs more often (esp https://capev2.readthedocs.io/en/latest/development/)

### CODE REVIEW

**Comment by TheMythologist** [comment]
Don't merge yet - it seems there's an issue with dependencies

**Comment by TheMythologist** [comment]
Removing poetry pre-commits as they're still in beta (it actually ruins the lock file)

**Comment by TheMythologist** [comment]
Yup ready for merge

**Comment by TheMythologist** [comment]
Ready for merge :)

**Comment by doomedraven** [comment]
thank you a lot for all your work

**Pull request merged**
