### PR TITLE
Fix file copy

### PR DESCRIPTION
**Pull request by enzok**

### CODE REVIEW

**Comment by doomedraven** [comment]
@cccs-kevin ?

**Comment by cccs-kevin** [comment]
Wow @enzok , so you're saying that if the archive had a flat structure, that those files weren't being copied to C:?

**Review by cccs-kevin — APPROVED** [review]

**Comment by kevoreilly** [comment]
Thanks all 🙏

**Comment by cccs-kevin** [comment]
@enzok is 🎅

**Comment by enzok** [comment]
> Wow @enzok , so you're saying that if the archive had a flat structure, that those files weren't being copied to C:?

Yes the root files were excluded. Only sub dirs where copied.

**Pull request merged**
