### PR TITLE
Update cape2.sh

### PR DESCRIPTION
**Pull request by demon-i386**
added plocate (command locate) and libvirt-dev (python libvirt requirement)

### CODE REVIEW

**Comment by doomedraven** [comment]
hello, we don't need `libvirt-dev`, what os do you use that requires that library?

**Comment by demon-i386** [comment]
> hello, we don't need `libvirt-dev`, what os do you use that requires that library?

ubuntu 22.04

**Comment by cccs-kevin** [comment]
I needed the `libvirt-dev` package also

**Comment by doomedraven** [comment]
ok i did check, if you install `libvirt-dev` it forces install of `libvirt0`, any of my servers doesn't have that library. so i won't poison install script

**Pull request closed without merging**
