### PR TITLE
Evented signature filtering fix

### PR DESCRIPTION
**Pull request by cccs-mog**
Fixed the evented signature filtering to act like a AND instead of an OR which would falsely make some signature trigger their on_call.

### CODE REVIEW

**Comment by doomedraven** [comment]
oh thank you for work on that, i still recovering from flu so my brain was pretty off

**Comment by doomedraven** [comment]
so is still draft or as latest commit say is done?

**Comment by cccs-mog** [comment]
Sorry for the confusion, the commit comment done meant ready for internal code review. Should be removed from draft very soon !

**Comment by doomedraven** [comment]
thanks for your work on this

**Comment by cccs-mog** [comment]
Sorry took longer than expected but here it is !

**Comment by doomedraven** [comment]
thank you very much

**Pull request merged**
