### PR TITLE
Azure standard vmss fix

### PR DESCRIPTION
**Pull request by cccs-mog**

### CODE REVIEW

**Comment by ChrisThibodeaux** [comment]
Following. I am deploying via Azure, let me know if you want a hand testing.

**Comment by cccs-mog** [comment]
Hi @ChrisThibodeaux, yes hand testing would be good. This is still a work in progress so any feedback is appreciated. I unfortunately don't much time to work on this so any help is more than welcome.

**Comment by doomedraven** [comment]
Should we merge this one?

**Comment by ChrisThibodeaux** [comment]
@doomedraven Could you give me a couple hours on this one? I am a tiny bit concerned with the changes with quotas.

It may prevent my setup from being able to scale.

**Comment by ChrisThibodeaux** [comment]
@cccs-mog If my quota limit is 10vCPU and my machines each have 2vCPU, would it ever scale beyond a single instance?

I haven't had a chance to pull this and test yet today, so just curious if you know off-hand.

**Comment by cccs-mog** [comment]
Probably not. Yeah that number is quite high for small setup and would make sense to be able to lower/edit as a config value. @ChrisThibodeaux

**Comment by doomedraven** [comment]
any time that you need :)thanks

**Comment by ChrisThibodeaux** [comment]
@doomedraven Thanks, all done on my end.

@cccs-mog Working wonderfully, loving the quota check. I'd seen error logs crop up dealing with quota limits before, so this gives peace of mind. Cheers!

**Comment by doomedraven** [comment]
i guess you need to push PR?

**Comment by doomedraven** [comment]
or this one?

**Pull request merged**
