### PR TITLE
Updating MITRE TTPs

### PR DESCRIPTION
**Pull request by para0x0dise**
# Main Issue: Outdated TTPs
The hardcoded TTPs within the signatures, specifically in versions V6 and V7, have become outdated. The manual modification of each individual TTP poses a cumbersome task. Therefore, I have implemented a solution where I parse all the TTPs within these signatures, update them accordingly, and consolidate them into a configuration file named `TTPs.conf`. 

During the signature triggering process, I intercept the collection of all TTPs and update them using the config file. Then, I dump the updated results into the JSON report, ensuring accuracy and relevance.

## UPDATE-1: Duplicated Signatures
Multiple TTPs could be associated with a single signature, resulting in duplication when generating reports. To address this issue effectively, I devised a solution by grouping each signature together with its corresponding list of TTPs, thereby eliminating any redundant information and enhancing the clarity and conciseness of the reports.

## UPDATE-2: Inclusion of Sub-Technique IDs
I have included a test file that serves the purpose of mapping old TTPs to their corresponding new ones, while also incorporating sub-techniques into the mapping process.

### CODE REVIEW

**Comment by doomedraven** [comment]
hello thank you ,but i see a lot of missing things here, so please review your PR again

**Comment by para0x0dise** [comment]
@doomedraven 
I'm sorry, I modified the PR and waiting for your review.
Thanks

**Comment by doomedraven** [comment]
np, thanks for update, i will check that later today/this week, just went back from PTO

**Comment by doomedraven** [comment]
let me know once you done to check this

**Comment by para0x0dise** [comment]
@doomedraven 
I'm done. You can review it.

**Comment by doomedraven** [comment]
so by parts. 
some parts are moved to community as we won't maintain them. you just need to run `poetry run python utils/community.py -wa` to fetch them

tests/test_update_MITRE.py is now ->
https://github.com/CAPESandbox/community/blob/master/utils/TTPmap_updater.py as it doesn't have nothing to see with tests

the ttp config is here and is in json format, as i don't see reason to complicate it with config parsing when it can be that simple
https://github.com/CAPESandbox/community/commit/8cdfb42d54a84974d965890dc9a7d8984677b11a

fetch updates from community and your PR and check it, i did check of updater, still have to do last check on TTP map in core, but once that tested and it looks good for you im fine to merge that

**Comment by doomedraven** [comment]
ok so now there is another problem, as we had ttp and not ttps, mitre.py is broken fixing it

**Comment by doomedraven** [comment]
ok that fixed, what im not sure, why do you ignore the X.Y ttps?

**Comment by doomedraven** [comment]
ok this is well tested by me, if you are fine with my changes i will merge. or if you have any suggestions let me know

**Comment by para0x0dise** [comment]
@doomedraven 
I think we are good to merge. Thanks a lot for your tips.

**Pull request merged**
